[package]
name = "sq1-scrambler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "scrambler"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"
